### PR TITLE
[unitaryhack] Font scaling in labels of plot.matrix2d()

### LINKED ISSUE #129: Font scaling in labels of plot.matrix2d()
This issue is meant as a unitaryHACK bounty issue.
**Bounty**: $50

Function `plot.matrix2d()` is used when creating matrix element plots (it is called by qubit methods `<qubit>.plot_matrixelements()`). It has an argument `show_numbers` which explicitly adds text labels to indicate matrix element sizes. This example below shows how that works: 

    tmon2 = scq.Transmon(
        EJ=30.02,
        EC=1.2,
        ng=0.0,
        ncut=31
    )
    tmon.plot_matrixelements('cos_phi_operator', evals_count=10, show3d=False, show_numbers=True);

When too many levels are included, however, these labels start overlapping with each other, as in:

    tmon.plot_matrixelements('cos_phi_operator', evals_count=16, show3d=False, show_numbers=True);

We are looking for a small enhancement that adds simple logic to `plot.matrix2d()` which would scale the font size so that the text labels can be easily distinguished (within reason).
Ideally this modification should take into account the figure size, so that if more levels are being included, but the figure size is large enough, then the font used does not have to be extremely small.

### PR DESCRIPTION
**Pull request by golanor**
Closes #129  - the idea is to calculate the box size (from the matrix and figure size), and then take the font size to be the minimum between 8 (the current default) and the diagonal of the box.

### CODE REVIEW

**Comment by petergthatsme** [comment]
thanks for taking a stab at this. I was wondering if you thought about maybe also adding better "upward" scaling. For example right now something like this: 

    tmon = scq.Transmon(
        EJ=30.02,
        EC=1.2,
        ng=0.0,
        ncut=31
    )
    tmon.plot_matrixelements('cos_phi_operator', evals_count=3, show3d=False, show_numbers=True);

... will result in a text that's clearly way too small. So ideally, the font should be scaled down when many levels are requested, but it should also be scaled up somewhat when only a few levels are required. Any interest in adding a quick modification that would handle also such a case?

**Comment by golanor** [comment]
> thanks for taking a stab at this. I was wondering if you thought about maybe also adding better "upward" scaling. For example right now something like this:
> 
> ```
> tmon = scq.Transmon(
>     EJ=30.02,
>     EC=1.2,
>     ng=0.0,
>     ncut=31
> )
> tmon.plot_matrixelements('cos_phi_operator', evals_count=3, show3d=False, show_numbers=True);
> ```
> 
> ... will result in a text that's clearly way too small. So ideally, the font should be scaled down when many levels are requested, but it should also be scaled up somewhat when only a few levels are required. Any interest in adding a quick modification that would handle also such a case?

I did think about it, the issue is that it is less clear when to switch from one strategy to the other. If you have an idea how to do it i'll gladly add it to the code

**Comment by petergthatsme** [comment]
I had something like this in mind: 

    if show_numbers:
        fig_width, fig_height = fig.get_size_inches()
        box_width_inches = fig_width / matrix.shape[1]  
        font_size=box_width_inches * 12
        add_numbers_to_axes(axes, matrix, modefunction, fontsize=font_size)

...which does the right thing for fairly arbitrary (square) figure sizes, and arbitrary number of energy levels included. 
The idea is simply that given a 1 inch size box/cell, "by inspection", a font size of ~12 gives good text fit, then we can just scale this size ~12 by whatever box/cell size we end up with in a given problem.

One thing to add would be to handle non-square figure sizes where the ideal font size will depend on the smaller of box/cell height or box/cell width dimensions. For example this below will "fail" (i.e. text will not correctly fit) with the code above:

    fig, ax=plt.subplots(figsize=(8,3))
    tmon.plot_matrixelements('cos_phi_operator', evals_count=3, show3d=False, show_numbers=True, fig_ax=(fig, ax));

...but i think can be made to work with only a simple update to the scaling snippet. 
Let me know your thoughts on that.

**Comment by golanor** [comment]
So maybe something like

```python
if show_numbers:
    fig_width, fig_height = fig.get_size_inches()
    box_width_inches = fig_width / matrix.shape[1]  
    box_height_inches = fig_height / matrix.shape[0]
    font_size = min(box_width_inches, box_height_inches) * 12
    add_numbers_to_axes(axes, matrix, modefunction, fontsize=font_size)
```
would work for non-square figures?

**Comment by petergthatsme** [comment]
yup, you got it. 
Please add a pull request with that those changes, and I think we can close out the bounty!

**Review by golanor — COMMENTED** [review]
changed font size scaling to work for non square figures

**Comment by golanor** [comment]
> yup, you got it. Please add a pull request with that those changes, and I think we can close out the bounty!

is there anything else I should do with respect to this PR?

**Review by petergthatsme — APPROVED** [review]
thanks

**Comment by nathanshammah** [comment]
@golanor it seems like you have not signed up on unitaryHACK, please sign up to be able to claim the bounty https://airtable.com/shrJeycewBFqdot2B

**Pull request merged**
