### PR TITLE
Support for 1/f flux noise for Flux Qubit

### PR DESCRIPTION
**Pull request by golanor**
Hi,

This PR adds support for 1/f flux noise on `FluxQubit`, see #185 .
@petergthatsme  - I'm trying to understand what you wrote in the issue, what is the structure that I need to add to the unit tests? Should I add a `tphi_1_over_f` method to `FluxQubit`?

### CODE REVIEW

**Comment by petergthatsme** [comment]
Sorry for my slow response - I've been traveling (at an airport atm). 

Assuming you've added the "tphi_1_over_f_flux" (please note that I had a typo in the bounty description - was missing the "_flux" part of the sting) to the list returned by `FluxQubit.supported_noise_channels()`, to update the tests, you will have to also update `data['FluxQubit']` in `tests.test_noise.py` to account for the fact that (1) there is now a new supported noise channel, and (2) the `t1_effective()` and `t2_effective()` can get corrections from 1/f flux noise.  

Take a look at `tests/test_noise.py`, in particular `calc_coherence()` and `compare_coherence_to_reference()`

... and don't hesitate to let me know if something's not clear.

**Comment by golanor** [comment]
> Sorry for my slow response - I've been traveling (at an airport atm).
> 
> Assuming you've added the "tphi_1_over_f_flux" (please note that I had a typo in the bounty description - was missing the "_flux" part of the sting) to the list returned by `FluxQubit.supported_noise_channels()`, to update the tests, you will have to also update `data['FluxQubit']` in `tests.test_noise.py` to account for the fact that (1) there is now a new supported noise channel, and (2) the `t1_effective()` and `t2_effective()` can get corrections from 1/f flux noise.
> 
> Take a look at `tests/test_noise.py`, in particular `calc_coherence()` and `compare_coherence_to_reference()`
> 
> ... and don't hesitate to let me know if something's not clear.

I had the mistake of using `tphi_1_over_f` instead of `tphi_1_over_f_flux`. Once I corrected it, everything seems to work.

**Review by petergthatsme — APPROVED** [review]
looks good, thanks

**Review by petergthatsme — CHANGES_REQUESTED** [review]
@golanor  i noticed that you have two copies of  `d_hamiltonian_d_flux` implemented - i guess this is a typo?

**Comment by golanor** [comment]
> @golanor i noticed that you have two copies of `d_hamiltonian_d_flux` implemented - i guess this is a typo?

I guess so? I removed the redundant one.

**Pull request merged**
