### PR TITLE
Improvement on plot_transition()

### LINKED ISSUE #219: Enhancement of the `plot_transitions()` method
`plot_transitions()` is a method of class `ParameterSweepBase` which can be used for plotting energies associated with various transitions as a function of a scanned parameter. An example of how it can be used is presented [here](https://scqubits.readthedocs.io/en/v4.0/guide/parametersweep/ipynb/paramsweep2-transitions.html#Transition-plots).
 
We are looking to add an enhancement where one can pass lists of tuples as arguments `initial` and/or `final`, with **specific** state labels that represent initial and final transition end-points of transitions that should be plotted. So for example calling:

        sweep.plot_transitions(initial=[(1,2,4), (1,3,1)], final=[(0,1,0)])

should lead to (only) transitions between levels with labels (1,2,4)<->(0,1,0) and (1,3,1)<->(0,1,0) being plotted. 

These changes should not break current code, and should be documented in the method's docstring.

(It would of course be great, if this addition would be also briefly explained in the [documentation](https://github.com/scqubits/scqubits-doc) - but that is not part of the bounty).

### PR DESCRIPTION
**Pull request by anushkrishnav**
Fixes #219 

I have attached the notebook for more details on the issue I am facing  @petergthatsme

### CODE REVIEW

**Comment by petergthatsme** [comment]
thanks. First, as you can see above, the tests are failing, so maybe the first step could be to try to understand why, and fix if you can.

**Comment by anushkrishnav** [comment]
> thanks. First, as you can see above, the tests are failing, so maybe the first step could be to try to understand why, and fix if you can.

it was a simple issue fixed it

**Comment by petergthatsme** [comment]
just had a quick look. 
something like this: 
`sweep["ng":0.0].plot_transitions(initial=[(1,2,0), (1,2,1)], final=[(0,1,0)])`
fails with an error "Initial state must be lower than final state."
note this error does not make much sense in this context...  initial or final states can be anything as long as they only include energy levels that are present in the systems. 

Also, i already got the notebook, so please delete it from the PR (and update .gitignore). 

Note there is also another issue... things will break if there is actually no valid data to plot. Here an example would be running: `sweep["ng":0.0].plot_transitions(final=(1,1,2))`. 
This is present in the original code, and has always been a shortcoming... you don't have to fix it as part of the bounty; i will sort things out later. 
thx.

**Comment by anushkrishnav** [comment]
> just had a quick look. something like this: `sweep["ng":0.0].plot_transitions(initial=[(1,2,0), (1,2,1)], final=[(0,1,0)])` fails with an error "Initial state must be lower than final state." note this error does not make much sense in this context... initial or final states can be anything as long as they only include energy levels that are present in the system (by default we plot abs vals anyway).
> 
> Also, i already got the notebook, so please delete it from the PR (and update .gitignore).
> 
> Note there is also another issue... things will break if there is actually no valid data to plot. Here an example would be running: `sweep["ng":0.0].plot_transitions(final=(1,1,2))`. This is present in the original code, and has always been a shortcoming... you don't have to fix it as part of the bounty; i will sort things out later. thx.

got it i will fix these and send a pr shortly

**Comment by anushkrishnav** [comment]
Made the requested updates, the issue I can take it up at a later time if you have a way in mind.

**Comment by petergthatsme** [comment]
Thanks for taking the stab at this. I will accept this PR. 
To fix the other issue i mentioned, one would have to double check if there is any data to plot before plotting... In particular one has so check if `specdata.energy_table` is not empty, see `scqubits/utils/plotting.py:541`.

**Comment by anushkrishnav** [comment]
> Thanks for taking the stab at this. I will accept this PR. To fix the other issue i mentioned, one would have to double check if there is any data to plot before plotting... In particular one has so check if `specdata.energy_table` is not empty, see `scqubits/utils/plotting.py:541`.

Lets work on this, I will open a new PR

**Pull request merged**
