### PR TITLE
Oscillator lengths

### PR DESCRIPTION
**Pull request by dkweiss31**

### CODE REVIEW

**Review by jkochNU — APPROVED** [review]
Looks fine! @dkweiss31  Are you taking care of propagating this into the docs?

**Comment by dkweiss31** [comment]
Sorry @jkochNU just seeing this - not sure what you had in mind? For instance the function just above these helper functions  harm_osc_wavefunction doesn't appear anywhere in the docs

**Comment by jkochNU** [comment]
@dkweiss31 `harm_osc_wavefunction` is unlikely to be needed by the end user. I was assuming that your helper functions were meant for the end user. If that's accurate: something that's not in any example notebook and not in the docs is essentially non-existent for the user.

**Comment by dkweiss31** [comment]
I see - did you have a specific place in mind to mention this? Perhaps the notebooks are a better idea since there isn't a lot of discussion of `Oscillator` in the user guide

**Pull request merged**
