### PR TITLE
Added doc strings in documentation

### LINKED ISSUE #127: Adding code documentation
This issue is meant as a unitaryHACK bounty issue.

**Bounty**: $50

We would like to add more complete documentation to the scqubits source code. 

Here we ask for documenting signatures of 15 items such methods, functions, classes, etc, where the details are either incomplete, or missing completely.  
Documentation should follow standards observed by the rest of the code.

### PR DESCRIPTION
**Pull request by divshacker**
fixes #127

### CODE REVIEW

**Comment by divshacker** [comment]
I have added most of the doc strings, however I left some of the functions which I supposed not be defined as they are already well defined. @petergthatsme Let me know if you have any other changes required.
Thanks

**Comment by petergthatsme** [comment]
Thanks for taking a stab at this bounty. 

Maybe I can point out a few items that, when addressed, would allows us to merge these changes into the codebase. 

If possible: 
- Please add periods at end of sentences.
- Please use proper capitalization. For example, "Returns Interaction term string" should at the very least be something like "Returns the interaction term string." There are multiple instances of this kind of random capitalizations. 
- Please try to add complete descriptions, i.e., for those methods you've chosen to document, please include more than just a two word description (i.e., where at least it's clear what's returned for example, please add that information) 
- Please (where possible) try to use language that is consistent with what's currently in the code (although, there of course might be some inconsistencies). For example instead of "Eigen Vectors" please use "eigenvectors". 
- Where possible please try to keep comments no longer than ~80 characters per line. 
- For math symbols (eg, for what you call "Sigma Plus operator", it would be great to use sphinx math notation. You can read about it [here](https://documentation.help/Sphinx/math.html). This is because these expressions can then get properly rendered in the documentation. For example you can take a look at [this](https://scqubits.readthedocs.io/en/latest/api-doc/_autosummar/scqubits.core.transmon.Transmon.html), and then glance at the corresponding doc strings in the source [file](https://github.com/scqubits/scqubits/blob/master/scqubits/core/transmon.py). It should be very easy to see how math can be written. 

If you have some time to update things a little, we'd love to add your pull request to the main code base. 

Thanks again for giving this a go!

**Comment by divshacker** [comment]
Thanks for these suggestions, I can add some of the points that you suggested but like there are some function in which I completely don't know what's going on because I am new in this code base. I just need help, If you can just point out where more description is needed and suggested the exact text so that I can add it there please. So it will help me a lot.
Rest all I can manage. 
Thanks

**Comment by divshacker** [comment]
@petergthatsme Hey, I have opened this PR on 17th of June for Unitarty hack. But like unitary hack team are not agreed about accepting this PR. Please look into it if you can.

**Comment by petergthatsme** [comment]
Hi @divshacker 
I think the idea was that the bounties had to be finalized (i.e. PR accepted) close(ish) to the time when the hackathon ended (so around the 17th of June). This PR you've opened on the last day, is still, as of right now, probably rather far from being in a shape where we could merge it into the code base. So my guess is that's why you might not be able to get the funds. 

Either way, if you do continue working on it in the future, I'm of course happy to offer guidance, if needed... but unfortunately it might not involve financial compensation.

**Comment by jkochNU** [comment]
This PR appears stale at this point. If there is progress resolving problems notes, please open a new PR.

**Pull request closed without merging**
